import 'package:flutter/material.dart';

mixin AppColors {
  static const Color primaryGreen = Color(0xff008655); //Color(0xff78C155);
  static const Color primaryGreenOld = Color(0xff78C155);
  static const Color white = Color(0xffFFFFFF);
  static const Color textGreyDark = Color(0xff141F31);
  static const Color lightGrey = Color(0xffF5F5F5);
  static const Color textGreylight = Color(0xff818181);
  static const Color borderGrey = Color(0xffD8D8D8);
  static const Color primaryRed = Color(0xffED1C24);
  static const Color buttonDisabledGrey = Color(0xffD8D8D8);
  static final Color textBlack = const Color(0xff000000).withOpacity(0.5);
  static const Color textLinkBlack = Color(0xff00243C);
  static const Color backgroundLightGrey = Color(0xffF3F3F3);
  static const Color featureYellow = Color(0xffFFDA2D);
  static const Color statusYellow = Color(0xffF3DF39);
  static const Color statusGrey = Color(0xff707070);
  static const Color statusGreen = Color(0xffDCFFCB);
  static const Color black = Color(0xff000000);
  static const Color textBlue = Color(0xff2E6284);
  static const Color discountBlue = Color(0xff3352EE);
  static const Color demandCardBackground = Color(0xffFBFEFB);
  static const Color textGrayMedium = Color(0xff5F6C7B);
  static const Color iconGreyLight = Color(0xffA9A9AA);
  static const Color dashboardGradientFirst = Color(0xffEDE652);
  static const Color dashboardGradientSecond = Color(0xffCCD95B);
  static const Color dashboardGradientThird = Color(0xff5BB56B);
  static const Color dashboardGradientForth = Color(0xff3CAF6C);
  static const Color dataSelectorBackground = Color(0xffd5ffc1);
  static const Color getLoanBackground = Color(0xffF2F3F8);
  static const Color lastFilterBackground = Color(0x63636328);
  static const Color lastFilterTextColorBlack = Color(0xff0000E5);
  static const Color testBlack = Color(0x000000CC);
  static const Color lighterGrey = Color(0xffF8F8F8);
  static const Color statusRed = Color(0xffFF0000);
  static const Color tabsInactive = Color(0xff898989);
  static const Color polygonGreen = Color(0xffA7FF7D);
  static const Color toastColor = Color(0xff5F6C7B);
  static const Color darkGreen = Color(0xff3A8417);
  static const Color dateGrey = Color(0xff999999);
  static const Color textLinkBlackLight = Color(0xff123C58);
  static const Color textLinkBlackLighter = Color(0xff2E6284);
  static const Color statusOrange = Color(0xfffa862d);
  static const Color darkYellow = Color(0xffFFE87D);
  static const Color valGreen = Color(0xff008655);
  static const Color valTextGray = Color(0xff5F6C7B);
  static const Color valInactiveGray = Color(0xffF4F4F4);
  static const Color valBorders = Color(0xffD0D5DD);
  static const Color homeGrey = Color(0xffE9E9E9);
  static const Color homeTextGrey = Color(0xff5F6C7B);
  static const Color homeOtherFeatureBackground = Color(0xff008655);
  static const Color profileLighterGrey = Color(0xffD9D9D9);
  static const Color profileRed = Color(0xffE00800);
  static const Color mapButtonBackground = Color(0xffEEF7EA);
  static const Color myLandStatusYellow = Color(0xffF2A400);
  static const Color underReviewBackground = Color(0xffF7F0EA);
  static const Color rejectedBackground = Color(0xffF7EAEA);
  static const Color lighterBorderGreay = Color(0xffD1D1D1);
  static const Color lightBlack = Color(0xff242424);
  static const Color featurePurple = Color(0xffFF00F5);
  static const Color myLandsLightGrey = Color(0xffF5F5F7);
  static const Color brokerNoteBackground = Color(0xffCCE7DD);
  static const Color brokerBlack = Color(0xff212121);
  static const Color filterLightGrey = Color(0xffC6C6C6);
  static const Color auctionTimerBackground = Color(0xffF9F9F9);
  static const Color connectionBackground = Color(0xffE0F0EB);
  static const Color unselectedColor = Color(0xffEAECF0);
  static const Color fCoverGradient01 = Color(0xff38B779);
  static const Color fCoverGradient02 = Color(0xff5DC173);
  static const Color fCoverGradient03 = Color(0xffDFDC65);
  static const Color fCoverGradient04 = Color(0xffE6E760);
  static const Color trendingPurple = Color(0xff9747FF);
  static const Color walletSaveMoreBackground = Color(0xffE0F0EB);
  static const Color myPlanPlanCardBack = Color(0xffFFFCF5);
  static const Color myPlanTrendingCardBack = Color(0xff9747FF);
  static const Color myPlanUsageCardBorder = Color(0xffCCD3D8);
  static const Color planLineGrey = Color(0xffD7D7D7);

  static Color hexToColor(String code) {
    return Color(int.parse(code.substring(1, 7), radix: 16) + 0xFF000000);
  }
}
